<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
     <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                  izz="${m*r*r/2}" /> 
      </xacro:macro>

      <xacro:macro name="box_inertia" params="m x y z">
        <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(x*x+z*z)/12}" iyz = "0"
                  izz="${m*(x*x+y*y)/12}" /> 
      </xacro:macro>

      <xacro:macro name="sphere_inertia" params="m r">
        <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                  iyy="${2*m*r*r/5}" iyz = "0"
                  izz="${2*m*r*r/5}" /> 
 </xacro:macro>


 <xacro:macro name="wheel" params="lr tY">

  
     <joint name="${lr}_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${lr}_wheel"/>
        <!--origin rpy="0 0 0" xyz="${tY} 0 -${wheelRadius+chassisHeight/2}"/-->
        <origin xyz="0.0 ${tY} -0.125" rpy="-1.57 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>

       <link name="${lr}_wheel">

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
          </geometry>
          <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
          <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
          </geometry>
        </collision>

       <inertial>
      	<origin xyz="0 0 0" />
     	 <mass value="2.6" />
      	<inertia ixx="0.007042" ixy="0.0" ixz="0.0"
               iyy="0.007042" iyz="0.0"
               izz="0.01300" />
    	</inertial>

        <gazebo reference="${lr}_wheel">
	    <mu1>10.0</mu1>
	    <mu2>10.0</mu2>
	    <kp>500000.0</kp>
	    <kd>10.0</kd>
	    <maxVel>1.1</maxVel>
	    <material>Gazebo/Black</material>
        </gazebo>
	</link>
    </xacro:macro>

<xacro:macro name="caster_front" params="lr tY">

       <joint name="${lr}_caster_front_joint" type="fixed">
        <parent link="base_link"/>
        <child link="${lr}_front_wheel"/>
        <origin xyz="0.400 ${tY} -0.185" rpy="0 0 0"/>
       </joint>

       <link name="${lr}_front_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
          <geometry>
           <sphere radius="${casterRadius}" />
          </geometry>
          <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
          <geometry>
           <sphere radius="${casterRadius}"/>
          </geometry>
        </collision>

        <inertial>
          <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
          <mass value="${casterMass}"/>
          <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
        </inertial>
       </link>

     
      
      
        <gazebo reference="${lr}_front_wheel">
	    <mu1>0.0</mu1>
	    <mu2>0.0</mu2>
	    <kp>1000000.0</kp>
	    <kd>100.0</kd>
	    <maxVel>1.0</maxVel>
	    <material>Gazebo/Blue</material>
        </gazebo>

 </xacro:macro>

 <xacro:macro name="caster_back" params="lr tY">
   
     <joint name="${lr}_caster_back_joint" type="fixed">
        <parent link="base_link"/>
        <child link="${lr}_back_wheel"/>
        <origin xyz="-0.400 ${tY} -0.185" rpy="0 0 0"/>
	<axis xyz="0 0 1"/>
      </joint>

      <link name="${lr}_back_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
          <geometry>
           <sphere radius="${casterRadius}" />
          </geometry>
          <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
          <geometry>
           <sphere radius="${casterRadius}" />
          </geometry>
        </collision>
        <inertial>
       		<origin xyz="0 0 0.0" />
      		<mass value="0.01" />
      		<inertia ixx="0.001" ixy="0.0" ixz="0.0"
       	        	iyy="0.001" iyz="0.0"
               		izz="0.0001" />
       </inertial>
       </link>

      
      <gazebo reference="${lr}_back_wheel">
	    <mu1>1.0</mu1>
	    <mu2>1.0</mu2>
	    <kp>1000000.0</kp>
	    <kd>10.0</kd>
	    <maxVel>3.0</maxVel>
	    <material>Gazebo/Blue</material>
      </gazebo>
  </xacro:macro>


</robot>
